### ISSUE TITLE
大神能加下我使用后的需求吗

### ISSUE THREAD

**Issue by snaillovesmile** [QDong415/QKeyboardEmotionView#2]
1. 表情键盘的删除按钮增加长按删除手势，长按删除不需要的文字
2. if (!textView){
        //vc没有提供UITextView，我们自己来实现
        textView = [[UITextView alloc] initWithFrame:CGRectZero];
    }
.font 
把属性设置放到括号外面， 不然所有属性都要重写一遍，要是使用其他的字体大小， textView最小高度也要修改（否则不居中）
最好再给TextView加个placeholder属性。朋友圈评论会用到， 回复xxxx啥的

**Comment by snaillovesmile** [comment]
还有：非常感谢，这个开源组件， 使用效果确实很棒

**Comment by QDong415** [comment]
已开放到.h文件
