### ISSUE TITLE
键盘高度不准确

### ISSUE THREAD

**Issue by ghost** [QDong415/QKeyboardEmotionView#6]
如果给键盘下边放一个黑色的 maskView  键盘和输入框中间有一条黑线  表情键盘是正常的

**Comment by ghost** [comment]
![2361651453714_ pic_hd](https://user-images.githubusercontent.com/19161230/166173029-77376554-8b0d-453e-a6e2-3eac94a4de51.jpg)

**Comment by QDong415** [comment]
我没用过maskview，你在我最新的demo（2.0）版本上用maskView试一下正常吗，如果还是有问题，把工程发给我
