### ISSUE TITLE
请教大佬一个问题

### ISSUE THREAD

**Issue by ghost** [QDong415/QKeyboardEmotionView#7]
由于跟后端交互 都是转成了字符串[微笑] ,  但是实际显示的时候是😊,   如果连着的表情数量比较多， 有好几行，  通过boundingRect计算出来的高度就不对了， 计算出来的高度是[微笑]的高度 ， 但显示到界面上的是表情，表情其实没有这么高，表情越多相差越大，怎么才能正确获取到高度呢

**Comment by QDong415** [comment]
你是问UIlabel怎么计算表情的高度吗？需要先转为attributeString再boundingRect。你可以看下载看下我最新的2.0版本的 聊天界面的demo，ChatViewController里有demo
