### ISSUE TITLE
大神, 微信键盘有个文字 引用功能, 键盘弹出这里要显示引用文本, 能给点思路吗

### ISSUE THREAD

**Issue by snaillovesmile** [QDong415/QKeyboardEmotionView#9]

**Comment by QDong415** [comment]
有图吗

**Comment by snaillovesmile** [comment]
![WechatIMG52](https://user-images.githubusercontent.com/33648940/196075094-796e84e2-40ef-45dd-9cea-62fede692355.jpeg)

**Comment by SnailLoveSmile** [comment]
我个菜鸟, 计算的位置偏移总是不对, 555... 哎. 太折磨了..
